addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/misc.sp

https://github.com/Franc1sco/FixHintColorMessages/issues/9

fix memory leak

---

scripts/upgrade_scripts/upgrade-fluffy.sh

i guess someone made a typo +updated repo

fix for #2

---

addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/hooks.sp
addons/sourcemod/scripting/surftimer/trails.sp

Remove TF2 and Base64 Includes

---

README.md

I created this pull request mainly to get your input on the Repository description itself.
I've heard words that it's not ideal and I agree, but what do you propose to set the repository description to?
Also any improvements to this readme updates are welcome!

Update README.md - we dont support SM1.11

---

addons/sourcemod/scripting/surftimer/misc.sp

should help with issue #5 though creates a new issue with spacing between the bottom 2 lines on the HUD when the speed gradient returns to 0 it seems to mess up the spacing slightly

short coded colours

---

addons/sourcemod/scripting/surftimer/sql.sp

I made 2 if statements in sql.sp more clearer and fixed 2 possible sql injections in queries where previously client's name wasn't escaped.

refactor couple if statements and fix sql injections

---

.github/workflows/dev.yml
.github/workflows/release.yml

We this step, it's easier for us to build/release a package on the master branch and only on the master branch.

Split master.yml into release.yml and dev.yml

---

addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/misc.sp
addons/sourcemod/scripting/surftimer/timer.sp

RemoveEntity is new with 1.10 and much safer than RemoveEdict, fixing some crashes

RemoveEdict > RemoveEntity

---

scripts/mysql-files/checkpoints-upgrade.sql
scripts/upgrade_scripts/upgrade-fluffy.sh
scripts/upgrade_scripts/upgrade-nikooo.sh

this removes more old surftimer stuff
and checkpoint upgrade has the create index included

updated the Upgrade files

---

addons/sourcemod/scripting/surftimer/timer.sp
addons/sourcemod/translations/surftimer.phrases.txt

Just a small fix to move away from changelevel as you can sometimes get an issue with the map changing back to the same map. This can be fixed by an external plugin, however this way is a lot cleaner and is integrated into the timer for a natural map change.

Change Map Fixes

---

addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/scripting/surftimer/misc.sp
addons/sourcemod/scripting/surftimer/sql.sp
addons/sourcemod/scripting/surftimer/timer.sp

More changelogs here: https://github.com/olokos/Surftimer-olokos/commit/6bd9e875d6c955968fe48155901cfa10ca333e17
Close #109

Give server bit more time to retrieve the correct steamid

---

addons/sourcemod/translations/pl/surftimer.phrases.txt

@olokos plz check i'm illiterate

Polish translation

---

.github/workflows/dev.yml
.github/workflows/release.yml

@olokos read discord, you need to define GITHUB_TOKEN.

Create release and upload release package

---

.github/FUNDING.yml

Remove funding info

---

addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/scripting/surftimer/misc.sp
addons/sourcemod/scripting/surftimer/replay.sp

Here's a couple few minor fixes.
- Fixed fun styles being set back to normal movement after Command_Teleport action is called.
- Potential fix for the replay bug issue #76 but I am not too sure.
- Fix for the Spectator HUD sometimes glitching out and going off-center slightly and then moving back as well as changed back to the nicer colour format.

Minor Fixes

---

addons/sourcemod/scripting/surftimer/commands.sp

This adds freestyle to the !top menu.. my first time doing a github commit/pr, apologies if anything wasnt done correctly. Feel free to let me know.

Added freestyle to !top menu

---

addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/admin.sp
addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/scripting/surftimer/cvote.sp
addons/sourcemod/scripting/surftimer/misc.sp
addons/sourcemod/scripting/surftimer/replay.sp
addons/sourcemod/scripting/surftimer/sql.sp
addons/sourcemod/scripting/surftimer/sqltime.sp
addons/sourcemod/scripting/surftimer/timer.sp
addons/sourcemod/scripting/surftimer/vip.sp

Replace CloseHandle with delete

---

scripts/mysql-files/ck_maptier.sql

someone made an oopsie
fixes #173

ck_maptier.sql will now work

---

addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/scripting/surftimer/misc.sp

made mistakes
not tested
have fun

Added Style commands

---

addons/stripper/maps/surf_mesa.cfg
addons/stripper/maps/surf_ny_momentum_v3_1.cfg

Fixes this madness for surf_ny_momentum_v3_1

Stripper update to remove teleport triggers spamming console

---

addons/sourcemod/scripting/surftimer/buttonpress.sp
addons/sourcemod/scripting/surftimer/misc.sp

The discord messages will now be compared to SR
tested but as @sneak-it said 2 approvals are needed and i want someone else to test it as well

Fix discord msg

---

addons/stripper/maps/surf_boring.cfg
addons/stripper/maps/surf_lament_n2p.cfg
addons/stripper/maps/surf_singletons.cfg

Apologies this is the same as Multiple stripper updates #202. Just having some GitHub issues xD

Multiple stripper updates

---

.github/workflows/dev.yml
.github/workflows/release.yml

Workflow fix

---

addons/sourcemod/scripting/surftimer/commands.sp

NOT TESTED
@FR33K1LL could you test it?

Should fix #133

---

addons/sourcemod/scripting/surftimer/mapsettings.sp
addons/sourcemod/scripting/surftimer/misc.sp
addons/sourcemod/scripting/surftimer/sql.sp
addons/sourcemod/scripting/surftimer/sqltime.sp
addons/sourcemod/scripting/surftimer/vip.sp

I've also added a stock to check is a (old hndl) db is valid and error doesn't longer as 1.

Replace old DBI style with DBI methodmap

---

addons/sourcemod/scripting/surftimer/newmaps.sp

Fix error in sm_nm command

---

addons/sourcemod/scripting/surftimer/admin.sp
addons/sourcemod/scripting/surftimer/sql.sp

Primary result of my changes with valid client indexes through datapacks and queries. I reverted the requirement valid client indexes, hopefully it don't throw any errors (race conditions) with invalid client indexes.
#225

Fix Recalculation of Player Ranks

---

addons/sourcemod/scripting/surftimer/admin.sp
addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/scripting/surftimer/db/queries.sp
addons/sourcemod/scripting/surftimer/sql.sp

Just a quick Copy&Paste and a few changes to latest sql/query/style changes

Readd of wiping/reset player times

---

addons/sourcemod/scripting/surftimer/misc.sp

Show correct time for other non-normal styles

---

addons/sourcemod/scripting/surftimer/hooks.sp
addons/sourcemod/scripting/surftimer/misc.sp
addons/sourcemod/scripting/surftimer/timer.sp

I'm not pretty sure if it's enough, but test will not hurts.
#227

Set/show correct title type on chat/scoreboard

---

README.md

Rename to Surftimer-Official

---

addons/sourcemod/scripting/surftimer/sql.sp

Fix for issue #247

---

addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/translations/surftimer.phrases.txt

This stops you from "stacking" knives.
If you already have a knife and use !knife you will get a print to chat saying you have a knife.
If you do not have a knife you will be given one.

Improvement for #79

---

addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/buttonpress.sp
addons/sourcemod/scripting/surftimer/misc.sp
addons/sourcemod/translations/surftimer.phrases.txt

This is various changes to the way that player times are displayed. All examples of changes can be found in #1 
Im no coder but iv done my best. Please review and i hope you all approve.

Player time readout changes

---

addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/scripting/surftimer/cvote.sp
addons/sourcemod/scripting/surftimer/misc.sp
addons/sourcemod/scripting/surftimer/sql.sp
addons/sourcemod/scripting/surftimer/timer.sp

The dev branch has a lot of commits and fixes, many of them being things that not everyone should run. However, there are a few fixes in the branch that ought to be in the master branch since they are easy to test and resolve issues that have been in the timer since 285 or improve the way some things are done.
This pull request aims to merge some of the simpler fixes and commits from the dev branch, so people don't need to manually cherry-pick these commits themselves when cloning SurfTimer. (Since we are actively merging things into the master branch, I figured this would be a good thing to do!)
_Full disclosure: this is my first time cherry-picking commits to actually pull request, so I hope I did this right ahah_

Merge some fixes from the dev branch to master

---

.github/workflows/master.yml
addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/convars.sp

By default all new convars will not added to already exist config files. This custom include fix this pretty annoying and confusing "bug".

Add AutoExecConfig support

---

addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/buttonpress.sp
addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/scripting/surftimer/convars.sp
addons/sourcemod/scripting/surftimer/hooks.sp
addons/sourcemod/scripting/surftimer/misc.sp
addons/sourcemod/scripting/surftimer/sql.sp
addons/sourcemod/scripting/surftimer/surfzones.sp
addons/sourcemod/translations/surftimer.phrases.txt

Practice rework

---

addons/sourcemod/scripting/surftimer/admin.sp
addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/scripting/surftimer/sql.sp

Source/Credits: https://github.com/qawery-just-sad/Surftimer-Official/commit/ad18ac21de0142ce765da6d2dcc1efad78785a77

Add wipeplayer command

---

addons/sourcemod/scripting/surftimer/commands.sp

.....sorry it was triggering me too much

Correct a very minor typo in the side-HUD modules menu

---

addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/convars.sp
addons/sourcemod/scripting/surftimer/replay.sp

- move replay variables and more comments
- more dynamic array size
- fix my memory leak since last PR :worried:
- fix ConVar doesn't change
https://discord.com/channels/366959507764674560/425362754959048726/890668208539963392

several fixes

---

addons/sourcemod/scripting/surftimer/convars.sp

fix change noclipspeed causes DispatchAsyncEvent spam

---

addons/sourcemod/scripting/surftimer/surfzones.sp

Fix typo in the zones menu

---

addons/sourcemod/scripting/surftimer/convars.sp
addons/sourcemod/scripting/surftimer/misc.sp

**** : when i set a record as a test the units of the run on the bot are like 200 more units than what i had on 285 surftiemr they match fine its weird

fix replay hud speed

---

addons/sourcemod/scripting/surftimer/admin.sp
addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/scripting/surftimer/misc.sp

Add command to reload player rank table per console

---

addons/sourcemod/scripting/surftimer/replay.sp

Skip -1 index as startFrame tick

---

addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/translations/surftimer.phrases.txt

Add /teleprev and /telenext

---

addons/sourcemod/scripting/surftimer/commands.sp

I forgot to add this in my last PR, sorry haha

Add IsValidClient check to teleprev/next

---

addons/sourcemod/scripting/surftimer/db/queries.sp

Removed multiple SET

---

README.md
addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/convars.sp
addons/sourcemod/scripting/surftimer/hooks.sp
addons/sourcemod/scripting/surftimer/misc.sp

- Remove pushfix
- Remove slopefix
- Update README.md - organize Installation and Requirements section, add recommended movement-related plugins

Remove old code

---

addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/buttonpress.sp
addons/sourcemod/scripting/surftimer/misc.sp
addons/sourcemod/translations/surftimer.phrases.txt

Fixes the sound bug #375 
Haven't actually tested it but it should work.

No sounds bug

---

scripts/mysql-files/downgrade/checkpoints_dev.sql

If you get errors with the drop column query, delete them from the file.
Tested by @freakexeuLow and me
**Make backup before you use this. Usage at your own risk!**

Add dowgrade file for newer checkpoints (and other changes)

---

addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/scripting/surftimer/misc.sp
addons/sourcemod/translations/surftimer.phrases.txt

Fix for https://discord.com/channels/366959507764674560/375452719529328644/943892552032059433

Teleport fix

---

addons/sourcemod/scripting/surftimer/commands.sp

also limit command_tostage duh

---

addons/sourcemod/translations/surftimer.phrases.txt

Max Savelocs changed to 128 but translation file never got updated.
That's the only thing ¯\_(ツ)_/¯

changed translation 1024 -> 128

---

addons/sourcemod/scripting/surftimer/commands.sp

Fix command argument getting to make `sm_dr surf_mesa_fix` work properly

Small fix in sm_dr

---

addons/sourcemod/scripting/surftimer/misc.sp

Thanks to [Phoenix/komashchenko](https://hlmod.ru/resources/fix-hint-color-messages.1416/) for publishing this.

Fix center hud

---

addons/sourcemod/scripting/surftimer/misc.sp

- IsClientConnected contains in IsClientInGame
- IsValidEntity isn't really needed here

Remove 2 checks from IsValidClient

---

addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/include/surftimer.inc
addons/sourcemod/scripting/surftimer/api.sp
addons/sourcemod/scripting/surftimer/commands.sp

Added a return for which bonus the client is currently on.
Small fixes for g_iInBonus[client]

Native_GetPlayerInfo - add bonus level

---

addons/sourcemod/scripting/surftimer/hooks.sp

Small cleanup of the say_hook function

Cleaned up say_hook

---

addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/hooks.sp
addons/sourcemod/scripting/surftimer/replay.sp
addons/sourcemod/scripting/surftimer/surfzones.sp

- fix [error spams](https://pastebin.com/nLGqLefa) if no ticks.
- fix not gonna ignore triggers
- can't help renaming something

replay stuff fix

---

addons/sourcemod/scripting/surftimer/sql.sp

Fix tables upgrades which stop after the first upgrade

---

addons/sourcemod/scripting/surftimer/misc.sp
addons/sourcemod/scripting/surftimer/surfzones.sp

probably won't wanna hard code stripper fixes into the timer lol

remove simple stripper fixes

---

addons/sourcemod/scripting/surftimer/commands.sp

This almost gave me a heart attack last night when I saw my console flooded with SELECT queries cause someone was deleting recs :)

disable 'debug' message?

---

addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/scripting/surftimer/misc.sp
addons/sourcemod/translations/surftimer.phrases.txt

Allows players to use the cmd ```sm_startpos``` in stage zones

Stage sm_startpos

---

addons/sourcemod/scripting/surftimer/misc.sp

as per https://discord.com/channels/366959507764674560/379572504542445568/991169174007189504

fix array out of bounds error when teleporting to !end

---

addons/sourcemod/scripting/surftimer/misc.sp

missing case for the sm_end fix

missing case

---

addons/sourcemod/translations/surftimer.phrases.txt

remove duplicate "ReplayFinishingMsg" from translations

remove duplicate object key

---

addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/db/updater.sp
addons/sourcemod/scripting/surftimer/globals.sp
addons/sourcemod/scripting/surftimer/sql.sp
addons/sourcemod/scripting/surftimer/timer.sp

#469
this seems to have fixed it for me, but ya never know xD

fix for mysql timeout

---

addons/sourcemod/scripting/surftimer/timer.sp

@tslashd found this error
which was due to a valid client check not being done before printing
apologies for my 1iq :)

missing check for printing msg

---

addons/sourcemod/scripting/surftimer/commands.sp

fix center speed display flashing

---

addons/sourcemod/scripting/surftimer/replay.sp

index was wrong
i.e - when selecting stage 5 would replay from stage 4
thx @tslashd for noticing

fix wrong selected checkpoint on replays 

---

addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/scripting/surftimer/surfzones.sp

disable practice mode on client command rather than starttouch & don't allow startpos if in practice mode

Fix saveloc exploit 

---

addons/sourcemod/scripting/surftimer/surfzones.sp

The variable  `runtime` was being set with wrong values

PR info bug fix

---

addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/scripting/surftimer/sql.sp
addons/sourcemod/translations/surftimer.phrases.txt

#486 
displays the amount of points required to achieve next rank
also prints msg if the player is already max rank

sm_nextrank

---

addons/sourcemod/scripting/surftimer/sql.sp

after #472 sm_cpr was not working, queries were using old layout

fix for sm_cpr

---

addons/sourcemod/scripting/surftimer/sql.sp

wrong index was because i forgot that bonuses are inserted to ck_checkpoints

wrong index v2

---

addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/scripting/surftimer/globals.sp
addons/sourcemod/scripting/surftimer/sql.sp
addons/sourcemod/translations/surftimer.phrases.txt

same functionality like already existing ```sm_ctop``` but for continents

sm_continenttop

---

addons/sourcemod/scripting/surftimer/db/queries.sp
addons/sourcemod/scripting/surftimer/sql.sp

error prior to fix
issues were:
* query to update had wrong column name `cp` instead of `time`
* query size was too low
* query formating had missing 'cp' value
thx @tslashd for helping out on this (:

db_UpdateCheckpoints() fix

---

addons/sourcemod/scripting/surftimer/commands.sp

Preespeed mode menu fix

---

addons/sourcemod/configs/surftimer/skillgroups.cfg

add relative information to skillgroups.cfg

---

addons/sourcemod/scripting/include/surftimer.inc
addons/sourcemod/scripting/surftimer/api.sp
addons/sourcemod/scripting/surftimer/buttonpress.sp

this time i didnt touch any other methods in the api (pls dont kill me), just adding a completly new one :)

api for bonus data

---

addons/sourcemod/scripting/surftimer/newmaps.sp
addons/sourcemod/scripting/surftimer/sql.sp

Usage of sizeof instead of hardcoded size

Use LogStackTrace instead of LogError

---

README.md
addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/misc.sp

Embedded looking for the radar image and adding it to download table to avoid usage of external plugins only for this matter.

Add radar images to DownloadTable

---

addons/sourcemod/scripting/surftimer/hooks.sp

If ``ck_chat_enable`` is 0, we can not read input text for some commands, e.g. ``.dr``

Fix chat processor for our commands

---

addons/sourcemod/scripting/SurfTimer.sp
addons/sourcemod/scripting/surftimer/convars.sp
addons/sourcemod/scripting/surftimer/db/updater.sp
addons/sourcemod/scripting/surftimer/mapsettings.sp
addons/sourcemod/scripting/surftimer/misc.sp
addons/sourcemod/scripting/surftimer/sql.sp

For anyone who are interested which query takes how much time.
Here's the precompiled version based on latest **dev** branch:
[SurfTimer.zip](https://github.com/surftimer/SurfTimer/files/9692807/SurfTimer.zip)

Log query times

---

addons/sourcemod/scripting/surftimer/commands.sp
addons/sourcemod/scripting/surftimer/globals.sp
addons/sourcemod/scripting/surftimer/misc.sp
addons/sourcemod/scripting/surftimer/sql.sp
addons/sourcemod/scripting/surftimer/surfzones.sp

disable practice mode instantly on client teleport commands, add new bool for practice prints, add some fail-safes for inserting times (probably not needed, but won't hurt regardless)

practice mode changes

---

addons/sourcemod/scripting/surftimer/sql.sp

**/mi** was erroring out cause of missing mapper name argument

Missing mapper name argument for Map Info

---

scripts/mysql-files/fresh_install.sql

`mapper` column in `ck_maptier`

fresh_install update

---

addons/sourcemod/scripting/surftimer/globals.sp

https://github.com/surftimer/SurfTimer/issues/550

increase cplimit from 37 to 100
