addons/sourcemod/scripting/surftimer/mapsettings.sp
> Samatazz: should add a command to allow all zones more than one jump instead of manually setting them in each zone setting
>  Samatazz: i didnt mean a command to disable the anti bhopping for every map globally, just a command to update it for specific maps where you need to bhop more than once e.g surf_omnific
=> added onejumplimit remover to mapsettings

addons/sourcemod/scripting/surftimer/sql.sp
This solves an SQL error when your server name has symbols or quote marks in it by properly escaping the value of `hostname`.
=> Fix SQL Hostname Error

addons/sourcemod/scripting/surftimer/db/queries.sp, addons/sourcemod/scripting/surftimer/misc.sp, addons/sourcemod/scripting/surftimer/sql.sp
This PR has two fixes from my personal fluffyst fork
1. Fix to !startpos on staged maps
The startpos command has a bug where, on a staged map, if you have set a custom start position, the commands to switch stages (e.g. !s, !back) will not bring you to the stage - it will just teleport you to the custom startpos. This bug is fixed
2. Significant speed-up for single user profile load
Profile load tends to be very slow on maps with a large stage/cp count with several clears. This is due, in part, to poor query design. Ranks, for example, are calculated by selecting all clear times faster than the player, sorting them, then returning that to the plugin. The plugin then does a GetRowCount'. This can be significantly improved by simply using SELECT COUNT(*) instead. This commit implements this …
=> Bug Fix and DB Query optimization for profile loading

addons/sourcemod/scripting/SurfTimer.sp, addons/sourcemod/scripting/surftimer/hooks.sp
Fixes #42 
The bhop detection logic is very sub-par and should be re-worked. This should be thoroughly tested, even though I checked to make sure that this patched the exploit.
=> Fix prespeed exploit

addons/sourcemod/scripting/SurfTimer.sp
Self explanatory, some time ago Valve added new radio commands, this blocks those new ones.
=> Add new radio commands to block list

README.md, addons/sourcemod/scripting/SurfTimer.sp, addons/sourcemod/scripting/surftimer/hooks.sp, addons/stripper/global_filters.cfg
PR'ing this because it is a breaking change. 
Since CK's inception, there has been a hardcoded "entity kill list". These entities are:
```
"logic_timer",
"team_round_timer",
"logic_relay",
"player_weapon_strip",
"player_weaponstrip",
```
Several of these (the top 3 notably) are present on old ported Jail maps, which would teleport everyone to a jail after X minutes, or after someone has finished the map first. It is good to remove these globally, however there are a few maps that break, or have missing features due to stripping these entities blindly.
With Stripper, you can still remove these entities globally, but you can also re-add necessary entities back through map-specific files if need be. In the timer's current state, you would just be SOL.
With this PR, I removed the entity kill …
=> Remove hardcoded entity kill list, suggest Stripper

addons/sourcemod/scripting/surftimer/misc.sp
Fixes the bug #3 Stops ALL sounds being played if the user has it turned off in their configs
=> quake sounds fix

addons/sourcemod/scripting/surftimer/db/queries.sp, addons/sourcemod/scripting/surftimer/sql.sp
After reading [ashakiri's](https://github.com/olokos/Surftimer-olokos/commit/6de0d5bab72a898e7bf5a11362e1f4f4bd8c482c) post detailing the poor performance of using the GetRowCount() function I have gone through and replaced it with faster FetchInt() and FetchFloat() functions, along with modifying the original queries to support the use of FetchInt() and FetchFloat().
I have also heavily modified the SQL_db_CalcAvgRunTimeCallback() function which, for some reason, was loading the entire runtimepro column (12000+ entries on one of my servers alone) to derive the average from the column using a while loop. I've replaced this with a new query in queries.sp that simply returns the average from the column and have modified sql.sp to work with this value, if there was some method to the while …
=> Further optimizations to sql.sp

.github/workflows/master.yml, addons/sourcemod/scripting/SurfTimer.sp, addons/sourcemod/scripting/include/colorlib_map.inc, addons/sourcemod/scripting/surftimer/hooks.sp, addons/sourcemod/scripting/surftimer/misc.sp, tools/colors.yaml
ColorLib on [Github](https://github.com/c0rp3n/colorlib-sm) and on [AlliedModders](https://forums.alliedmods.net/showthread.php?t=320842)
Reason for ColorLib:
> The reason for this is that Colors and More Colors both make heavy use of many ReplaceString operations each one looping through the buffer being formatted, whereas this could be avoided by writing a single pass formatter as used here and was done for ColorVariables.
And to why replace ColorVariables? it also adds extra overhead with forwards and allowing for more "dynamic" colors, which isnt always needed.
[Source](https://forums.alliedmods.net/showthread.php?t=320842)
=> Replace ColorVariables with ColorLib

addons/sourcemod/scripting/surftimer/misc.sp
The char array in PrintCSGOHUDText is filled with '\n' characters but the final character must be null.
=> Make sure buffer is null terminated at PrintCSGOHUDText

addons/sourcemod/scripting/surftimer/db/queries.sp, addons/sourcemod/scripting/surftimer/sql.sp
It seems like this fork of the timer has never had the ability to delete the previous bot file? That's very odd so I've added this as well as when you delete a record, instead of just deleting the .rec and being done with it, it'll restore the previously stored record.
=> Restore Previous Records

addons/stripper/maps/surf_beyond.cfg
Reverts surftimer/Surftimer-olokos#191
@sneak-it 
``
the vscript that was deleted sets the player's velocity to 0 0 0 so that drops are fixed between stages
has nothing to do with gravity and is a map feature, which many maps should objectively have
idk if beyond has player clip boxes to stop people from telehopping or not but now you have to snipe teleporters to ensure you get the best time in a map run
that one change completely alters existing map times
the gravity thing is a temp fix i suppose but that in the end should be adapted to the timer so we don't have to stripper 'fix' every single map that has a gravity change
but the velocity thing is just dead wrong
``
=> Revert "Fix beyond styles"

addons/sourcemod/scripting/surftimer/commands.sp
Fix duplicate and breaking fixbot permissions check, allow to be used via server console
=> Fix fixbot command

addons/sourcemod/scripting/surftimer/hooks.sp
This is more of a band-aid than anything else.
This does allow you to get more than 1 jump in whilst not moving or moving at a very low speed <100u/s however when moving at speed that actually matters then it seems to work as it should. 
I spent 10+ mins jumping in a zone and i could not break it. I also was not in any way able to use this to my advantage.
=> One_jump_limit-Band-aid

addons/sourcemod/scripting/surftimer/surfzones.sp
fixes https://github.com/surftimer/Surftimer-Official/issues/108
ty https://github.com/t5mat
=> fix hookzone issue

addons/sourcemod/scripting/surftimer/hooks.sp
I figured out a way to extend the existing pre-hop prevention to accommodate the slower styles (Low-Gravity and Slow-Motion) by adding cTime thresholds that meet the style's requirements when checking for whether a player is currently in a bhop.
I initially tried re-working the system in agreement with sneaK's comment that the current system is pretty bad, but I ended up just giving up and trying to extend the current system. Until we get a full re-work, this should prevent pre-hopping in both Low-Gravity and Slow-Motion.
cTime Measurements:
=> Add LG/SM cTime thresholds for prehop prevention

addons/sourcemod/scripting/surftimer/sql.sp
This is a super quick fix for the completed maps list in profiles always displaying Rank 1 instead of the correct rank.
After replacing SQL_GetRowCount:
=> Replace SQL_GetRowCount with SQL_FetchInt in SQL_ViewAllRecordsCallback2

addons/sourcemod/scripting/surftimer/sql.sp
This is a tiny modification to the queries used in the `db_selectPlayerRank` function. When players use the `/rank @#` command to check someone's rank and points in the chat, the `db_selectPlayerRank` can display style ranks and points, often leading to confusion.
A good example of this can be seen in the screenshots below. The first screenshot showcases the `/rank @1` command before this fix - the expected result should be "w", but we instead see Dini's slow motion top rank and score.
With this fix, issuing the same command gives us the expected results:
=> Specify style = 0 when running db_selectPlayerRank

addons/sourcemod/scripting/surftimer/hooks.sp, addons/sourcemod/scripting/surftimer/sql.sp
https://discord.com/channels/366959507764674560/379572504542445568/887331585563701298
=> fix for [Surftimer] SQL Error (db_selectPlayerRankCallback) error

addons/sourcemod/scripting/SurfTimer.sp, addons/sourcemod/scripting/surftimer/buttonpress.sp, addons/sourcemod/scripting/surftimer/convars.sp, addons/sourcemod/scripting/surftimer/hooks.sp, addons/sourcemod/scripting/surftimer/misc.sp, addons/sourcemod/scripting/surftimer/replay.sp, addons/sourcemod/scripting/surftimer/sql.sp, addons/sourcemod/scripting/surftimer/timer.sp
Sometimes the bots bug when a player cuts a trigger/wall too close, and it has been bothering us for a long time:rage:
Also, this problem can be traced back to the time since cksurf use **velocity** and **angle** to store our replay
(pretty worse legacy:joy:)
some like #20 #98 point it out directly but no one solve.
This PR cost me a half day, and here's what i'm mainly doing
- Replace the function with methodmap
- **Support the old replay** version(0x01) while using the new version(0x02)
- Write and load new replay based on **position** and **angle**:blush::blush::blush:
- Delete useless(unused) sentences and improve something
**I haven't done enough testing yet**, may have bugs
but hope that there's something change since this pr :persevere::persevere::persevere:.
=> Update and fix replay

addons/sourcemod/scripting/surftimer/surfzones.sp
Currently, the timer disables Practice Mode for a player only when they exit the start zone. This has left room for an exploit in the current release that allows players to bypass limitations placed in the start-zone as a result of still being in Practice Mode after failing. 
Since `g_bPracticeMode[client]` is still true when a player is in the start-zone after failing, they can bypass the prespeed limiter and prehop infinitely to give themselves a massive advantage. (i.e, players can enter practice mode, fail by hitting a reset trigger, and then prehop infinitely in the start zone.)
This pull request turns off Practice Mode for a player when they enter a start zone rather than when they exit one. This prevents the above exploit from being possible.
=> Disable practice mode when player touches a map/bonus start zone.

addons/sourcemod/scripting/SurfTimer.sp
Added a few radio commands to block. Mainly gets rid of pings, chatwheel commands, and the moaning radio command.
=> Disable playerradio and ping radio commands

addons/sourcemod/scripting/surftimer/convars.sp, addons/sourcemod/scripting/surftimer/misc.sp
player can not disable their hud when dead, even if they already set their timer's sidehud or centre hud to **[OFF]**
=> fix hud cant be disabled when player's dead

addons/sourcemod/scripting/surftimer/hooks.sp
To resolve #114,
This PR implements what @timyc mentioned in the above issue. It allows zoners to use Max Speed zones and takes into account the actual speed set. 
From my testing, this also seems to make MaxSpeed zones work when they didn't before.
Here's a quick video of me testing it: [Streamable](https://streamable.com/c02cc5)
=> Resolve #114 - Update LimitMaxSpeed in hooks to use the correct MaxSpeed value

addons/sourcemod/scripting/surftimer/replay.sp
Since PR #325, the replays system relies on the `g_iSelectedReplayStyle` and `g_iSelectedBonusReplayStyle` variables to determine what style the current replay bot is in to correctly calculate and display the bot's speed.
These variables are only set when a player uses the `sm_replay` command. However, after the system is done showing the replay to the player, it returns back to the default replay bot (or in the cases of bonuses, cycles through replays for each bonus). These are all in normal style, but since those style variables are never reset, the speed on those bots are entirely wrong if someone were to spectate the bots casually without using `sm_replay`.
This PR just makes sure those two variables are correctly reset before the bots cycle back to the usual replays after showing the …
=> Reset SelectedReplayStyle variables in automatic replay loop

.github/workflows/master.yml, .github/workflows/release.yml
SurfTImer requires these to be defined:
```cpp
// Additional color names for ckSurf backwards compatibility
SetTrieString(hTrie, "bluegray", "\x0A"); // using bluegrey
SetTrieString(hTrie, "gray", "\x08"); // using gray
SetTrieString(hTrie, "gray2", "\x0D"); // using gray2
SetTrieString(hTrie, "orange", "\x10"); // using gold
SetTrieString(hTrie, "steelblue", "\x0D"); // using grey2
SetTrieString(hTrie, "pink", "\x0E"); // using orchid
SetTrieString(hTrie, "lightblue", "\x0A"); // using bluegrey
SetTrieString(hTrie, "olive", "\x05"); // using lightgreen
```
Just correcting the workflows to use the right include file for colors (to be more specific, this PR makes it use the one linked in the compile requirements in the README.)
=> Use the correct colorvariables include file in workflows

addons/sourcemod/scripting/surftimer/hooks.sp
I've talked briefly about this in #350 - this pull request adds a simple check to ensure that the zoneID is valid before attempting to limit speed when the player is in a MaxSpeed zone.
=> LimitMaxSpeed only when zoneID is not below zero, attempt to resolve #350

addons/sourcemod/scripting/surftimer/buttonpress.sp, addons/sourcemod/scripting/surftimer/commands.sp, addons/sourcemod/scripting/surftimer/misc.sp, addons/sourcemod/scripting/surftimer/sql.sp, addons/sourcemod/scripting/surftimer/surfzones.sp
This PR adds a new stock `EmitSoundToClientNoPreCache` which allows to play a sound to a client without having to precache that sound.
This takes advantage of [this CSGO quirk](https://wiki.alliedmods.net/Csgo_quirks#The_.22play.22_client_command).
It was already implemented in the plugin, the PR just makes it more declarative through a stock.
```c
/**
* Emit a sound to a client without having to precache the sound.
* See https://wiki.alliedmods.net/Csgo_quirks#The_.22play.22_client_command for more details.
* 
* @param client      The client's id.
* @param szPath      The path of the sound with or without "play " as a suffix.
* @param addPlay     Whether or not "play " should be append to the begining of szPath (default = true).
*/
stock void EmitSoundToClientNoPreCache(int client, const …
```
=> Add a new stock for clarity and remove an old stock

addons/sourcemod/scripting/surftimer/misc.sp
There is an issue with the **HUD** when you are passing through a checkpoint and times switch to **+** or **-** comparisons, the last digit of _**Speed:**_ would disappear along with _**u/s**_.
After some testing I came to the conclusion that this is due to character limit in the **HUD**, so I went on a quest to save some characters. By removing the spaces between _**Stage: %i / i%**_ and _**Rank: %i / i%**_ that issue was gone but it needed a little bit more as it was still cutting off last digit and I removed the space whenever **+** or **-** comparisons appear. But even after all of that it was still cutting off _**u/s**_, so I removed it as it flashes on and off when passing through stages/checkpoints which is distracting and altogether not cool (sue me).
Removing those spaces caused …
=> Center HUD Fixes #1

README.md, addons/sourcemod/scripting/SurfTimer.sp, addons/sourcemod/scripting/surftimer/buttonpress.sp, addons/sourcemod/scripting/surftimer/commands.sp, addons/sourcemod/scripting/surftimer/hooks.sp, addons/sourcemod/scripting/surftimer/misc.sp, addons/sourcemod/scripting/surftimer/sql.sp, addons/sourcemod/scripting/surftimer/timer.sp
- **Calculate times using client ticks instead of GetGameTime()** - Time should be calculated based on the number of executed playercmds and not server frames, since multiple playercmds (or none) may be processed in a single server frame. [Also, GetGameTime() is weird and returns a lag compensated value (?)](https://hlcoders.valvesoftware.narkive.com/IG3IBv9m/gpglobals-curtime). In any case, this change makes times independent of lag.
- **Make checkpoints accuracy higher than 0.1s** - Before, checkpoint times were only updated in 0.1s intervals (??)
- **Make EndTouchFix a requirement** - The engine calls EndTouch()s at the end of each server frame, not after each ProcessMovement. So if multiple playercmds are processed in 1 frame, trigger EndTouch calls might be delayed by a few client …
=> Make times accurate

addons/sourcemod/scripting/SurfTimer.sp
`MAX_NAME_LENGTH` is 128
UTF-8 character can take from 1 to 4 bytes to store, so if player has 8 and more 4-byte characters in his nickname (`𒂱𒂲𒂳𒂴𒂵𒂶𒂷𒂸𒂹𒂺𒂻` for example), we will have to lose some characters saving his movement to .rec file (`𒂸𒂹𒂺𒂻` from this example).
This change will not affect the reading of already written files.
If you think this change is not important: A few months ago I was working on a program that parses .rec files, this was a serious problem when the byte string ended unexpectedly and therefore could not be translated into a unicode string
=> Increase size of string

addons/sourcemod/scripting/surftimer/sql.sp
the `sizeof` returned 66 (`MAXPLAYERS + 1`, the first field) instead of the desired 1024 (the second field) of `g_szCustomTitleColoured` which is defined like this:
https://github.com/surftimer/Surftimer-Official/blob/584571d07ff3e8b0f6b70bdd7a8a851a3ebae626/addons/sourcemod/scripting/SurfTimer.sp#L420
If someone had a very long custom title due to using a lot of colors, for example:
`{darkred}R{lightred}A{red}I{orange}N{yellow}B{lightgreen}O{green}W{blue}S{darkblue}Y{purple}A{pink}Y`
it got cut off at 66 characters due to this. Sometimes it even led to the nickname not being displayed in chat.
=> Fix custom titles being truncated at 66 characters

addons/sourcemod/scripting/SurfTimer.sp, addons/sourcemod/scripting/surftimer/buttonpress.sp, addons/sourcemod/scripting/surftimer/commands.sp, addons/sourcemod/scripting/surftimer/misc.sp, addons/sourcemod/scripting/surftimer/surfzones.sp, addons/sourcemod/translations/surftimer.phrases.txt
https://discord.com/channels/366959507764674560/379572504542445568/414184575879610368
https://github.com/surftimer/Surftimer-Official/commit/d7892b7aadbbde5a4d8f6802471f7be5791c12a7
P.S. some of this code is useless
https://github.com/surftimer/Surftimer-Official/blob/7a59681913f04adb2e43e91fd55c5d355cc167a4/addons/sourcemod/scripting/surftimer/buttonpress.sp#L838-L842
At the end of the last stage, it increases by one (to `g_TotalStages + 1`), but immediately after that it returns to the total number of stages on map (to `g_TotalStages`)
https://github.com/surftimer/Surftimer-Official/blob/7a59681913f04adb2e43e91fd55c5d355cc167a4/addons/sourcemod/scripting/surftimer/buttonpress.sp#L844-L847
However, due to the fact that `g_bWrcpEndZone[client]` is not reset after `client`'s connecting, …
=> Stage 2 bug refix

addons/sourcemod/scripting/surftimer/api.sp
There were a couple of issues with this native that caused it to misbehave, mainly incorrect handling of reference variables: https://discord.com/channels/366959507764674560/425362754959048726/969005020592869406
This PR makes the native actually work. Has been tested, @tslashd watched me blow my brains out figuring stuff out 😆
=> Fix Native_GetPlayerData

addons/sourcemod/scripting/surftimer/sql.sp
A [recent commit](https://github.com/surftimer/SurfTimer/commit/a7768e1ba4e64faa624cfe5a711ae8ceb4b682fb#r75944129) prevented players from setting a custom title if their custom title wasn't already enabled. This PR re-adds the insert statement if the database does not have any rows matching a Steam ID.
=> Fix Player Titles

addons/sourcemod/scripting/surftimer/commands.sp, addons/sourcemod/scripting/surftimer/misc.sp, addons/sourcemod/scripting/surftimer/sql.sp
Note: There is an [open (stale) issue](https://github.com/surftimer/SurfTimer/issues/217) suggesting the removal of this stock.
- Updates all references of the g_bVip array to use the proper `IsPlayerVip` stock to check for VIP.
- Updates all command checks to provide feedback for if the player is not VIP.
- Updates the VIP check itself to check upon calling whether the player has the VIP flag, rather than depending only on the cached array and titles. (**this may cause unintended behavior, I haven't looked thoroughly into custom titles and their expected behavior/implications**)
=>  Update all VIP checks to use proper stock

addons/sourcemod/scripting/SurfTimer.sp, addons/sourcemod/scripting/surftimer/buttonpress.sp, addons/sourcemod/scripting/surftimer/commands.sp, addons/sourcemod/scripting/surftimer/convars.sp, addons/sourcemod/scripting/surftimer/hooks.sp, addons/sourcemod/scripting/surftimer/replay.sp, addons/sourcemod/scripting/surftimer/surfzones.sp
- This PR adds up to **X** amount of seconds prestrafe for all new replays that are recorded (Maps, Bonuses, Stages)
- Convar created to control the amount per server
- Prevents replays to contain lots of unnecessary data (people sitting AFK in any start zone)
- Prevents stage replays to start from end of previous stages
Does **NOT** break any already existing replays to **MY** knowledge - more testing needed on this part
Not all debug messages have been turned off, nor has been the command which I added in order to check ticks while in-game.
If anyone wants to test on a live server lmk to remove them :)
Here are some replay files produced using this same fork: [replays-with-pre.gz](https://github.com/surftimer/SurfTimer/files/8880024/replays-with-pre.gz)
might as well tag myself #387
=> Add pre to all replay recordings 

addons/sourcemod/scripting/surftimer/sql.sp
Updates the proper formatting of `db_selectBonusTopSurfers` to match the positional arguments of the new SQL query.
`char sql_selectTopBonusSurfers[] = "SELECT db2.steamid, db1.name, db2.runtime as overall, db1.steamid, db2.mapname FROM ck_bonus as db2 INNER JOIN ck_playerrank as db1 on db2.steamid = db1.steamid WHERE db2.mapname = '%s' AND db2.style = %i AND db1.style = %i AND db2.runtime > -1.0 AND zonegroup = %i ORDER BY overall ASC LIMIT 100;";` (mapname, style, style, zone).
=> Update bonus menu

addons/sourcemod/scripting/surftimer/mapsettings.sp
Currently `ck_chat_record_type` goes back to `0` which is default value set in code if the map reloads `mp_restartgame`
=> dont reload ck_chat_record_type

addons/sourcemod/scripting/include/surftimer.inc, addons/sourcemod/scripting/surftimer/api.sp, addons/sourcemod/scripting/surftimer/sql.sp
Current output of the forward _(excluding client)_
```
Style: 7 ; Time: 00:02:32 ; Diff: -00:00:77 ; Stage: 1 ; Float Time: 1.992200
```
Also tested this with `SurfTimer-Discord 2.1.3` turned on (without any edits to it) and it works fine announcing the record in Discord:
=> add fRunTime to WRCP forward

addons/sourcemod/scripting/surftimer/commands.sp, addons/sourcemod/scripting/surftimer/misc.sp
without this clients can possibly set a "legit" time by pressing !r when they reach endzone
=> wait 1 tick before disabling practice mode

addons/sourcemod/scripting/surftimer/sql.sp
https://github.com/surftimer/SurfTimer-discord/issues/21
=> wrong query to get style map record

addons/sourcemod/scripting/surftimer/commands.sp, addons/sourcemod/scripting/surftimer/db/queries.sp, addons/sourcemod/scripting/surftimer/replay.sp, addons/sourcemod/scripting/surftimer/sql.sp
error occuring before 
was due to wrong query format resulting in a false positive regarding duplicate entry
added a check to not display the starting points from replay incase there was no replay cp ticks found when loading
also swapped multiple queries to a unique transaction instead
=> Fix Replays with CP selected

addons/sourcemod/scripting/surftimer/sql.sp
Cross-check whether maps are present in current `ck_maptier` pool when getting total **Bonuses** and **Stages** for profiles.
**g_pr_StageCount * 2** ?? 
(ty @DaLLuZZ 🐱)
=> Stages and Bonuses count queries

addons/sourcemod/scripting/surftimer/sql.sp
wrong index when reloading checkpoint data whenever a player would improve pb/sr
forgot to PR yesterday xD - reported by @tslashd (:
=> wrong indexing

addons/sourcemod/scripting/surftimer/buttonpress.sp, addons/sourcemod/scripting/surftimer/globals.sp, addons/sourcemod/scripting/surftimer/misc.sp, addons/sourcemod/scripting/surftimer/sql.sp, addons/sourcemod/translations/surftimer.phrases.txt
previous pr fix for this in hindsifghted i believe was missing a few more things (til)
* fix for wrong PERSONAL record query
* fix for wrong position to send new record forward
=> fix for #524

addons/sourcemod/scripting/surftimer/globals.sp
if database name is greater than 32 then will get following error
[SM] Exception reported: More/Less then 1 rows? RowCount: 0, Table: ck_bonus, Column: runtime [SM] Blaming: SurfTimer.smx
[SM] Call stack trace:
[SM]   [0] SetFailState
[SM]   [1] Line 241, surftimer/db/updater.sp::SQLCheckDataType
=> increase database name length

addons/sourcemod/scripting/surftimer/sql.sp
Currently prestige rank kicks people out if they are not lower or higher than the set value in the cvar.
**Not tested**
Example:
- Set this to 50
- You are rank 50 and join the server, you get kicked
- Set it to 51
- You are allowed in the server
=> Fix ck_prestige_rank (missing = operator)

addons/sourcemod/scripting/surftimer/misc.sp
Today i have been trying to configure my surf server.
I wanted to have my own SPONSOR title and another one for the users with z flag (Admin).
I only been able to load the first tag on the file. After doing a lot of debug, i could see that it wont loop over all the items so i made these changes to be able to load multiple default titles.
=> Fix LoadDefaultTitle (only load the first one)

addons/sourcemod/scripting/surftimer/sql.sp
fix for sql_selectRankedPlayersRankCallback having no result (no rank) players would be kicked from the server if the convar was set to 0
=> ck_prestige_rank fix

addons/sourcemod/scripting/surftimer/sql.sp
Tried out both current queries and proposed ones from the suggestion on **surf_highlands**, results:
_Current_
```
[SurfTimer] : Finished sql_selectTotalBonusCountCallback in: 0.048828
[SurfTimer] : Finished sql_selectTotalStageCountCallback in: 0.048828
```
_Proposed_
```
[SurfTimer] : Finished sql_selectTotalBonusCountCallback in: 0.048828
[SurfTimer] : Finished sql_selectTotalStageCountCallback in: 0.039062
```
=> Query optimization from #506
